title: Estado operacional de Texto-Plano
buildFuture: true
defaultContentLanguage: es
languageCode: es
baseURL: https://estado.texto-plano.xyz
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: SSH
      category: Servidor principal
      partial: ""
    - name: BBJ
      category: Servidor principal
    - name: Web
      description: Servidor nginx con a web principal más otras como la del podcast y
        las de los usuarios están aquí.
      category: Servidor principal
      link: https://texto-plano.xyz/
    - name: Wiki
      description: La wiki de Texto-Plano
      category: Servidor principal
      link: https://wiki.texto-plano.xyz/
    - name: Gemini
      category: Servidor principal
    - name: Gophernicus
      category: Servidor principal
    - name: Radio
      category: Servidor principal
      link: http://texto-plano.xyz:8000
    - name: Mumble tilde
      category: Servidor principal
    - name: Jabber
      category: Servidor principal
      description: Protocolo XMPP para chatear en conferencia y uno a uno.
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: profile.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Servidor principal
      description: El tilde mismo, está localizado en el centro de datos de Vultr en Miami
      closed: false
  description: Monitoreamos continuamente el estado de los servicios del tilde y
    si hubiera cualquier problema se publicará una nota aquí.
  enableCustomHTML: false
  useLargeHeaderDesign: false
